[package]
name = "rs-crypto"
version = "0.1.0"
authors = ["ph04"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9.3"
rsa = "0.3.0"
rand = "0.8.3"
